Use an LXC container instead of Docker for testing

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,93 +1,73 @@
 language: python
-
+python: "2.7"
 sudo: required
 dist: trusty
-group: edge
-
-services:
-  - docker
 
 matrix:
   fast_finish: true
 
+addons:
+  apt:
+    sources:
+    - sourceline: 'ppa:ubuntu-lxc/stable'
+    packages:
+    - python-pip
+    - lxc
+    - lxc-templates
+    - yum
+    - expect-dev
+
+cache:
+  directories:
+    - $HOME/lxc/
+  pip: true
+
+before_cache:
+  - mkdir $HOME/lxc
+  - sudo tar cf $HOME/lxc/cache.tar /var/cache/lxc/
+  - sudo chown $USER. $HOME/lxc/cache.tar
+
 env:
-  - IMAGE_BUILD_PLATFORM=stable-centos7
-  - IMAGE_BUILD_PLATFORM=devel-centos7
+  - LXC_NAME=test-centos7 LXC_DISTRO=centos LXC_RELEASE=7
 
 install:
-  - npm install -g validate-dockerfile
+  # Install ansible
+  - pip install ansible
+
+  # Check ansible version
+  - ansible --version
+
+  # Create ansible.cfg with correct roles_path
+  - printf '[defaults]\nroles_path=../\nhost_key_checking=False' >ansible.cfg
+
+  # Extract LXC image cache
+  - sudo tar xf $HOME/lxc/cache.tar -C / || echo "Didn't extract cache."
+
+  # Create and configure LXC container to test against
+  - export LXC_ROOTFS=/var/lib/lxc/$LXC_NAME/rootfs
+  - '[ "x${LXC_DISTRO}" == "xdebian" ] && sudo LANG= LC_ALL= LC_CTYPE= lxc-create -n $LXC_NAME -t debian -- -r $LXC_RELEASE --mirror http://mirrors.us.kernel.org/debian --packages python || true'
+  - '[ "x${LXC_DISTRO}" == "xcentos" ] && sudo root_expire_password=no lxc-create -n $LXC_NAME -t centos -- -R $LXC_RELEASE || true'
+  - '[ "x${LXC_DISTRO}" == "xubuntu" ] && sudo lxc-create -n $LXC_NAME -t ubuntu -- -r $LXC_RELEASE --mirror http://mirrors.us.kernel.org/ubuntu --packages python || true'
+  - 'sudo lxc-start -n $LXC_NAME && until (sudo lxc-info -n $LXC_NAME | grep -q ^IP:); do printf . && sleep 1; done && sleep 2'
+  - '[ "x${LXC_DISTRO}" == "xcentos" ] && sudo lxc-attach -n $LXC_NAME -- yum install -y epel-release || true'
+  - sudo /bin/bash -c "printf '\n$(sudo lxc-info -Hin $LXC_NAME) test.lxc' >> /etc/hosts"
+  - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
+  - sudo mkdir -vm 0700 $LXC_ROOTFS/root/.ssh/
+  - sudo cp -v ~/.ssh/id_rsa.pub $LXC_ROOTFS/root/.ssh/authorized_keys
 
 script:
-  # TESTDIR = Where the stable-centos/Dockerfile is located
-  - export TESTDIR=tests
-  # ROLETOTEST = The name of this repo
-  - export ROLETOTEST=$(basename $(pwd))
-  - export COMMIT=${TRAVIS_COMMIT::8}
-  # The tag we assign the docker image we build with the Dockerfile
-  - export REPO=csc/ansible
-  # https://www.npmjs.com/package/validate-dockerfile - validate the Dockerfile
-  - docklint ${TESTDIR}/${IMAGE_BUILD_PLATFORM}/Dockerfile
-  # Build the image
-  - docker build -t ${REPO}:${IMAGE_BUILD_PLATFORM} ${TESTDIR}/${IMAGE_BUILD_PLATFORM}/
-  # Launch the container
-  - docker run --privileged -d -ti -e "container=docker"  -v `pwd`:/$ROLETOTEST -v /sys/fs/cgroup:/sys/fs/cgroup  ${REPO}:${IMAGE_BUILD_PLATFORM}  /usr/sbin/init
-  - DOCKER_CONTAINER_ID=$(docker ps | grep ${IMAGE_BUILD_PLATFORM} | awk '{print $1}')
-  - docker logs $DOCKER_CONTAINER_ID
-# Prepare test environment and print some more debug out
-  - docker exec -ti $DOCKER_CONTAINER_ID /bin/sh -c 'sudo yum -y install make && mkdir -p /opt/ansible/'
-  - docker exec -ti $DOCKER_CONTAINER_ID /bin/sh -c 'if ! [ -d /opt/ansible/ansible ] || ! bash -c "cd /opt/ansible/ansible && git branch"; then git clone http://github.com/ansible/ansible.git /opt/ansible/ansible ; fi'
+  # Basic role syntax check
+  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
+
+  # Perform a test run with the playbook
+  - ansible-playbook tests/test.yml -i tests/inventory
+
+  # Perform a another test run with the playbook to check for idempotency
+  - 'unbuffer ansible-playbook tests/test.yml -i tests/inventory >/tmp/idempotency.log 2>&1'
   - >
-    export ANSIBLE_VERSION=$(docker exec -ti $DOCKER_CONTAINER_ID /bin/sh -c 'cd /opt/ansible/ansible && \
-       ansible-playbook --version | perl -n -e '\''if ( m/^ansible-playbook\s+([0-9\.]{1,7})/ ) { print $1 }'\'' | tr -d "\n" \
-    ')
-  - >
-    export GIT_COMMIT=$(docker exec -ti $DOCKER_CONTAINER_ID /bin/sh -c 'cd /opt/ansible/ansible && \
-       ansible-playbook --version | perl -n -e '\''if ( m/^ansible-playbook\s+[0-9\.]{1,7}\s+.*?([a-fA-F0-9]{7,40})/ ) { print $1 }'\'' | tr -d "\n" \
-    ')
-  - >
-    export GIT_TAG=$(docker exec -ti $DOCKER_CONTAINER_ID /bin/sh -c "cd /opt/ansible/ansible && \
-      git tag | grep $ANSIBLE_VERSION | grep -v rc | tr -d '\n' \
-    ")
-  - >
-    echo "Ansible Version: $ANSIBLE_VERSION"
-  - >
-    echo "git SHA: $GIT_COMMIT"
-  - >
-    echo "Tagged Release?: $GIT_TAG"
-  - >
-    echo "CHECKING OUT: ${GIT_COMMIT:-$GIT_TAG}"
-  - >
-    docker exec -ti $DOCKER_CONTAINER_ID /bin/sh -c "cd /opt/ansible/ansible &&
-       git checkout ${GIT_COMMIT:-$GIT_TAG} &&  git submodule update --init --recursive &&
-       git --no-pager log --decorate=short --pretty=oneline -n 1"
-  - >
-    docker exec -ti $DOCKER_CONTAINER_ID /bin/sh -c 'cd /opt/ansible/ansible &&
-       sudo pip install tox sphinx &&
-       sudo pip install paramiko PyYAML jinja2 httplib2 passlib nose mock '
-  # Testing of this ansible-role:
-  - docker exec -ti $DOCKER_CONTAINER_ID /bin/sh -c "/$ROLETOTEST/tests/test-in-docker-image.sh"
-#  - docker exec -ti $DOCKER_CONTAINER_ID /bin/sh -c 'cd /opt/ansible/ansible && make tests '
-#  - >
-#    docker exec -ti $DOCKER_CONTAINER_ID /bin/sh -c 'cd /opt/ansible/ansible/test/integration/ &&
-#       make -j 1 parsing test_var_precedence test_templating_settings includes test_hash test_handlers test_group_by '
-  - >
-    docker exec -ti $DOCKER_CONTAINER_ID /bin/sh -c 'echo -ne "------\nEND ANSIBLE TESTS\n------\nSystemD Units:\n------\n";
-       systemctl --no-pager --all --full status ;
-       echo -ne "------\nJournalD Logs:\n------\n" ;
-       sudo journalctl --catalog --all --full --no-pager'
-  - docker exec -ti $DOCKER_CONTAINER_ID /bin/sh -c 'sudo yum -y install tree'
-  - docker exec -ti $DOCKER_CONTAINER_ID /bin/sh -c 'tree /ansible*'
-  - docker ps -a
-  - docker stop $DOCKER_CONTAINER_ID
-  - docker rm -v $DOCKER_CONTAINER_ID
-#after_success:
-#  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
-#  - if [ "$TRAVIS_BRANCH" == "master" -a "$IMAGE_BUILD_PLATFORM" == "stable-centos7" ]; then docker tag ${REPO}:${IMAGE_BUILD_PLATFORM} $REPO:latest; fi
-#  - docker tag ${REPO}:${IMAGE_BUILD_PLATFORM} $REPO:travis-${TRAVIS_BUILD_NUMBER}
-#  - docker tag ${REPO}:${IMAGE_BUILD_PLATFORM} $REPO:${IMAGE_BUILD_PLATFORM}-${ANSIBLE_VERSION}
-#  - docker tag ${REPO}:${IMAGE_BUILD_PLATFORM} $REPO:${IMAGE_BUILD_PLATFORM}-${GIT_COMMIT:-$GIT_TAG}
-#  - docker push $REPO
-#  - "[ -e \"~/.docker/config.json\" ] && shred -n 30 -u -z ~/.docker/config.json"
+    tail /tmp/idempotency.log | grep -qP 'changed=0.*failed=0'
+    && (echo "Idempotence: PASS"; exit 0)
+    || (echo "Idempotence: FAIL"; cat /tmp/idempotency.log; exit 1)
 
 notifications:
   email: false
